// SPDX-License-Identifier: GPL-3.0-or-later
package pipeline

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/autogame-17/scribe-studio/backend/scribe/proofread"
	"github.com/autogame-17/scribe-studio/backend/scribe/runtime"
	"github.com/autogame-17/scribe-studio/backend/scribe/transcribe"
)

// SavedTranscript is what the editor consumes: the raw Whisper Result
// plus the list of glossary hits so the UI can paint light-green
// highlights without re-running the replacement pass.
type SavedTranscript struct {
	*transcribe.Result
	Hits []proofread.Hit `json:"hits,omitempty"`
}

// applyGlossary runs the deterministic replacement pass over the raw
// whisper result and produces a saved-transcript payload. The source
// Result is mutated in place (segments' Text field is rewritten), and
// FullText is reassembled from the updated segments.
func applyGlossary(g *proofread.Glossary, r *transcribe.Result) *SavedTranscript {
	if g == nil || r == nil {
		return &SavedTranscript{Result: r}
	}

	likes := make([]proofread.SegmentLike, len(r.Segments))
	for i, s := range r.Segments {
		likes[i] = proofread.SegmentLike{Index: i, Text: s.Text}
	}
	res := g.Apply(likes)

	var full strings.Builder
	for i, seg := range res.Segments {
		r.Segments[i].Text = seg.Text
		if i > 0 {
			full.WriteByte('\n')
		}
		full.WriteString(seg.Text)
	}
	r.FullText = full.String()

	return &SavedTranscript{Result: r, Hits: res.Hits}
}

// saveTranscriptJSON writes the post-glossary transcript to
// AppSupport/transcripts/<taskID>.json. Editor + Export both read it.
func saveTranscriptJSON(taskID string, payload *SavedTranscript) (string, error) {
	dir, err := runtime.TranscriptsDir()
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, taskID+".json")
	raw, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// saveSRT writes `{video}.zh.srt` next to the original video so
// players (IINA, VLC, mpv) auto-load it.
func saveSRT(videoPath string, r *transcribe.Result) (string, error) {
	base := strings.TrimSuffix(videoPath, filepath.Ext(videoPath))
	lang := r.Language
	if lang == "" {
		lang = "und"
	}
	path := base + "." + lang + ".srt"
	var b strings.Builder
	for i, seg := range r.Segments {
		fmt.Fprintf(&b, "%d\n%s --> %s\n%s\n\n",
			i+1,
			formatSRTTime(seg.Start),
			formatSRTTime(seg.End),
			strings.TrimSpace(seg.Text),
		)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// saveMD writes a minimal Markdown transcript next to the video.
// Segments become paragraphs; timestamps go inline as subtle cues.
func saveMD(videoPath, title string, r *transcribe.Result) (string, error) {
	base := strings.TrimSuffix(videoPath, filepath.Ext(videoPath))
	lang := r.Language
	if lang == "" {
		lang = "und"
	}
	path := base + "." + lang + ".md"

	headline := title
	if headline == "" {
		headline = filepath.Base(base)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", headline)
	fmt.Fprintf(&b, "> Generated by Scribe — model %s, language %s, %s\n\n",
		safeStr(r.Model), safeStr(r.Language), formatDuration(r.Duration))
	for _, seg := range r.Segments {
		fmt.Fprintf(&b, "**[%s]** %s\n\n",
			formatSRTTime(seg.Start),
			strings.TrimSpace(seg.Text),
		)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func safeStr(s string) string {
	if s == "" {
		return "(unknown)"
	}
	return s
}

func formatDuration(sec float64) string {
	if sec <= 0 {
		return "(duration unknown)"
	}
	if sec < 60 {
		return fmt.Sprintf("%.0fs", sec)
	}
	m := int(sec) / 60
	s := int(sec) % 60
	return fmt.Sprintf("%dm%02ds", m, s)
}

func formatSRTTime(sec float64) string {
	if sec < 0 {
		sec = 0
	}
	h := int(sec) / 3600
	m := (int(sec) % 3600) / 60
	s := int(sec) % 60
	ms := int((sec - float64(int(sec))) * 1000)
	return fmt.Sprintf("%02d:%02d:%02d,%03d", h, m, s, ms)
}
