// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sphkit} from '../models';
import {scribe} from '../models';
import {transcribe} from '../models';
import {pipeline} from '../models';

export function DownloadModel(arg1:string):Promise<void>;

export function GetConfig():Promise<sphkit.Config>;

export function GetProxyStatus():Promise<scribe.ProxyStatus>;

export function GetTranscribeSettings():Promise<scribe.TranscribeSettings>;

export function GetTranscript(arg1:string):Promise<transcribe.Result>;

export function GetVersion():Promise<scribe.VersionInfo>;

export function ListModels():Promise<Array<scribe.ModelSummary>>;

export function ListTasks(arg1:string,arg2:number,arg3:number):Promise<sphkit.TaskListResult>;

export function ListTranscripts():Promise<Array<pipeline.Job>>;

export function OpenInFinder(arg1:string):Promise<void>;

export function RetryTranscribe(arg1:string):Promise<void>;

export function SetAutoTranscribe(arg1:boolean):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
