// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';
import {proofread} from '../models';
import {external} from '../models';
import {sphkit} from '../models';
import {scribe} from '../models';
import {logbus} from '../models';
import {transcribe} from '../models';

export function AcceptFix(arg1:string,arg2:string,arg3:boolean):Promise<pipeline.SavedTranscript>;

export function AcceptNewTerm(arg1:string,arg2:string):Promise<proofread.Entry>;

export function AddExternalURL(arg1:external.AddRequest):Promise<external.Task>;

export function CancelExternal(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearProofreadCache():Promise<void>;

export function DeleteGlossary(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function ExportMD(arg1:string):Promise<string>;

export function ExportSRT(arg1:string):Promise<string>;

export function GetAISettings():Promise<proofread.AISettings>;

export function GetConfig():Promise<sphkit.Config>;

export function GetProxyStatus():Promise<scribe.ProxyStatus>;

export function GetTranscribeSettings():Promise<scribe.TranscribeSettings>;

export function GetTranscript(arg1:string):Promise<pipeline.SavedTranscript>;

export function GetVersion():Promise<scribe.VersionInfo>;

export function ListExternalTasks():Promise<Array<external.Task>>;

export function ListGlossary(arg1:string):Promise<Array<proofread.Entry>>;

export function ListLogs(arg1:number):Promise<Array<logbus.Entry>>;

export function ListModels():Promise<Array<scribe.ModelSummary>>;

export function ListTasks(arg1:string,arg2:number,arg3:number):Promise<sphkit.TaskListResult>;

export function ListTranscripts():Promise<Array<pipeline.Job>>;

export function OpenInFinder(arg1:string):Promise<void>;

export function ProofreadTranscript(arg1:string):Promise<proofread.ProofreadResult>;

export function RejectFix(arg1:string,arg2:string):Promise<void>;

export function RemoveExternal(arg1:string):Promise<void>;

export function ResolveURL(arg1:string,arg2:string):Promise<external.ProbeResult>;

export function RetryExternal(arg1:string):Promise<void>;

export function RetryTranscribe(arg1:string):Promise<void>;

export function SaveTranscript(arg1:string,arg2:Array<transcribe.Segment>):Promise<void>;

export function SetAISettings(arg1:proofread.AISettings):Promise<void>;

export function SetAutoTranscribe(arg1:boolean):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestAIConnection(arg1:proofread.AISettings):Promise<string>;

export function UpsertGlossary(arg1:proofread.Entry):Promise<proofread.Entry>;
