// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFix(arg1, arg2, arg3) {
  return window['go']['scribe']['App']['AcceptFix'](arg1, arg2, arg3);
}

export function AcceptNewTerm(arg1, arg2) {
  return window['go']['scribe']['App']['AcceptNewTerm'](arg1, arg2);
}

export function AddExternalURL(arg1) {
  return window['go']['scribe']['App']['AddExternalURL'](arg1);
}

export function CancelExternal(arg1) {
  return window['go']['scribe']['App']['CancelExternal'](arg1);
}

export function ClearLogs() {
  return window['go']['scribe']['App']['ClearLogs']();
}

export function ClearProofreadCache() {
  return window['go']['scribe']['App']['ClearProofreadCache']();
}

export function DeleteGlossary(arg1) {
  return window['go']['scribe']['App']['DeleteGlossary'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['scribe']['App']['DownloadModel'](arg1);
}

export function ExportMD(arg1) {
  return window['go']['scribe']['App']['ExportMD'](arg1);
}

export function ExportSRT(arg1) {
  return window['go']['scribe']['App']['ExportSRT'](arg1);
}

export function GetAISettings() {
  return window['go']['scribe']['App']['GetAISettings']();
}

export function GetConfig() {
  return window['go']['scribe']['App']['GetConfig']();
}

export function GetProxyStatus() {
  return window['go']['scribe']['App']['GetProxyStatus']();
}

export function GetTranscribeSettings() {
  return window['go']['scribe']['App']['GetTranscribeSettings']();
}

export function GetTranscript(arg1) {
  return window['go']['scribe']['App']['GetTranscript'](arg1);
}

export function GetVersion() {
  return window['go']['scribe']['App']['GetVersion']();
}

export function ListExternalTasks() {
  return window['go']['scribe']['App']['ListExternalTasks']();
}

export function ListGlossary(arg1) {
  return window['go']['scribe']['App']['ListGlossary'](arg1);
}

export function ListLogs(arg1) {
  return window['go']['scribe']['App']['ListLogs'](arg1);
}

export function ListModels() {
  return window['go']['scribe']['App']['ListModels']();
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['scribe']['App']['ListTasks'](arg1, arg2, arg3);
}

export function ListTranscripts() {
  return window['go']['scribe']['App']['ListTranscripts']();
}

export function OpenInFinder(arg1) {
  return window['go']['scribe']['App']['OpenInFinder'](arg1);
}

export function ProofreadTranscript(arg1) {
  return window['go']['scribe']['App']['ProofreadTranscript'](arg1);
}

export function RejectFix(arg1, arg2) {
  return window['go']['scribe']['App']['RejectFix'](arg1, arg2);
}

export function RemoveExternal(arg1) {
  return window['go']['scribe']['App']['RemoveExternal'](arg1);
}

export function ResolveURL(arg1, arg2) {
  return window['go']['scribe']['App']['ResolveURL'](arg1, arg2);
}

export function RetryExternal(arg1) {
  return window['go']['scribe']['App']['RetryExternal'](arg1);
}

export function RetryTranscribe(arg1) {
  return window['go']['scribe']['App']['RetryTranscribe'](arg1);
}

export function SaveTranscript(arg1, arg2) {
  return window['go']['scribe']['App']['SaveTranscript'](arg1, arg2);
}

export function SetAISettings(arg1) {
  return window['go']['scribe']['App']['SetAISettings'](arg1);
}

export function SetAutoTranscribe(arg1) {
  return window['go']['scribe']['App']['SetAutoTranscribe'](arg1);
}

export function StartProxy() {
  return window['go']['scribe']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['scribe']['App']['StopProxy']();
}

export function TestAIConnection(arg1) {
  return window['go']['scribe']['App']['TestAIConnection'](arg1);
}

export function UpsertGlossary(arg1) {
  return window['go']['scribe']['App']['UpsertGlossary'](arg1);
}
